export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY"
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const FETCH_CATEGORIES_PENDING = "FETCH_CATEGORIES_PENDING"
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"
export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST"
export const GET_CATEGORY_BY_ID_PENDING = "GET_CATEGORY_BY_ID_PENDING";
export const GET_CATEGORY_BY_ID_SUCCESS = "GET_CATEGORY_BY_ID_SUCCESS";
export const GET_CATEGORY_BY_ID_REQUEST = "GET_CATEGORY_BY_ID_REQUEST";
