export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY"
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const FETCH_CATEGORIES_PENDING = "FETCH_CATEGORIES_PENDING"
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"
export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST"