export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT"
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST"
export const GET_PRODUCT_BY_ID_PENDING = "GET_PRODUCT_BY_ID_PENDING";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
